version: '3.8'

services:
  app:
    image: my-express-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
